language: erlang

env:
  - LUA=""

branches:
  only:
    - master

install:
  - sudo apt-get install lua5.2
  # - sudo apt-get install luarocks
  # - sudo luarocks install luafilesystem
  # - sudo luarocks install busted

script: "lua test.lua"

notifications:
  email:
    recipients:
      - bhoustudio@gmail.com
    on_success: change
    on_failure: always